spring:
  datasource:
<<<<<<< HEAD
    url: jdbc:mysql://localhost:3306/you_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: ""
    password: ""
=======
    url: jdbc:mysql://localhost:3306/foyer_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: rahma
    password: 12570
>>>>>>> foyer_01

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

