spring:
  datasource:
    url: #{DBLINK}
    username: #{username}
    password: #{password}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
